name: condensed
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=2.2.1
  - numpy-base=2.2.1
  - openssl=3.0.15
  - pandas=2.2.3
  - pip=24.2
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - ase==3.24.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bibtexparser==1.4.3
      - bleach==6.2.0
      - celluloid==0.2.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dscribe==2.1.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fonttools==4.55.3
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - hypergraphx==1.7.7
      - hypernetx==2.4.0
      - idna==3.10
      - igraph==0.11.8
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==8.33.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - llvmlite==0.45.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mistune==3.1.2
      - monty==2025.3.3
      - mpmath==1.3.0
      - narwhals==1.30.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.62.0
      - openpyxl==3.1.5
      - orjson==3.11.3
      - overrides==7.7.0
      - packaging==24.2
      - palettable==3.3.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - plotly==6.0.0
      - pluggy==1.6.0
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.19.1
      - pymatgen==2025.6.14
      - pyparsing==3.2.1
      - pytest==8.4.0
      - python-json-logger==3.2.1
      - pyvista==0.44.2
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - referencing==0.36.2
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.23.1
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.12
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - scooby==0.10.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - spap==1.0.4
      - sparse==0.17.0
      - spglib==2.5.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tk==0.1.0
      - tomli==2.2.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - uncertainties==3.2.3
      - uri-template==1.3.0
      - urllib3==2.3.0
      - vtk==9.3.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13

